export const CATEGORY_OPTIONS = [
  { value: "ac-repair", label: "AC Repair & Service" },
  { value: "ac-repair-service", label: "AC Repair & Service" },
  { value: "admin-office-services", label: "Admin / Office Services" },
  { value: "alteration-services", label: "Alteration Services" },
  { value: "appliance-repair", label: "Appliance Repair" },
  { value: "assembly-services", label: "Assembly Services" },
  { value: "auto-electricians", label: "Auto Electricians" },
  { value: "av-specialist", label: "AV Specialist" },
  { value: "bakers-services", label: "Bakers Services" },
  { value: "beauty", label: "Beauty & Wellness" },
  { value: "beauty-services", label: "Beauty & Wellness" },
  { value: "bicycle-services", label: "Bicycle Services" },
  { value: "bricklaying-services", label: "Bricklaying Services" },
  { value: "building-construction", label: "Building & Construction" },
  { value: "business", label: "Business Services" },
  { value: "car-washing", label: "Car Washing" },
  { value: "carpenter", label: "Carpentry" },
  { value: "cleaning", label: "Cleaning" },
  { value: "cooking-home-chef", label: "Cooking / Home Chef" },
  { value: "decking", label: "Decking" },
  { value: "deep-cleaning", label: "Deep Cleaning" },
  { value: "delivery-pickup-services", label: "Delivery & Pickup Services" },
  { value: "draftsman", label: "Draftsman" },
  { value: "driver-chauffeur", label: "Driver / Chauffeur Services" },
  { value: "electrical", label: "Electrician" },
  { value: "events", label: "Events & Entertainment" },
  { value: "event-services", label: "Event Services" },
  { value: "fitness-trainers", label: "Fitness Trainers" },
  { value: "flooring-services", label: "Flooring Services" },
  { value: "florist", label: "Florist" },
  { value: "furniture-assembly", label: "Furniture Assembly" },
  { value: "gardening", label: "Gardening" },
  { value: "gate-installation", label: "Gate Installation" },
  { value: "general", label: "General" },
  { value: "handyperson", label: "Handyperson" },
  { value: "painting", label: "Home Painting" },
  { value: "home-automation", label: "Home Automation" },
  { value: "home-cleaning", label: "Home Cleaning" },
  { value: "home-theatre-services", label: "Home Theatre Services" },
  { value: "home_services", label: "Home Services" },
  { value: "interior-architecture", label: "Interior & Architecture" },
  { value: "it-support", label: "IT Support" },
  { value: "laundry-ironing", label: "Laundry & Ironing" },
  { value: "marketing", label: "Marketing & Design" },
  { value: "marketing-design", label: "Marketing & Design" },
  { value: "moving", label: "Moving & Delivery" },
  { value: "other", label: "Other" },
  { value: "packers-movers", label: "Packers & Movers" },
  { value: "pest-control", label: "Pest Control" },
  { value: "pet-care", label: "Pet Care" },
  { value: "photography", label: "Photography" },
  { value: "plumbing", label: "Plumbing" },
  { value: "receptionist-services", label: "Receptionist Services" },
  { value: "security-patrol", label: "Security Patrol" },
  { value: "security-services", label: "Security Services" },
  { value: "senior-care", label: "Senior Care / Elder Care" },
  { value: "senior-care-elder-care", label: "Senior Care / Elder Care" },
  { value: "sharpening-services", label: "Sharpening Services" },
  { value: "tech", label: "Tech Support" },
  { value: "tutoring", label: "Tutoring" },
  { value: "tutors", label: "Tutors" },
  { value: "water-tanker", label: "Water & Tanker Services" },
  { value: "water-tanker-services", label: "Water & Tanker Services" },
  { value: "writing-services", label: "Writing Services" },
];
