export const CATEGORY_OPTIONS = [
  { value: "ac-repair-service", label: "AC Repair & Service" },
  { value: "admin-office-services", label: "Admin / Office Services" },
  { value: "alteration-services", label: "Alteration Services" },
  { value: "assembly-services", label: "Assembly Services" },
  { value: "auto-electricians", label: "Auto Electricians" },
  { value: "av-specialist", label: "AV Specialist" },
  { value: "bakers-services", label: "Bakers Services" },
  { value: "beauty", label: "Beauty & Wellness" },
  { value: "bicycle-services", label: "Bicycle Services" },
  { value: "bricklaying-services", label: "Bricklaying Services" },
  { value: "building-construction", label: "Building & Construction" },
  { value: "business", label: "Business Services" },
  { value: "cleaning", label: "Cleaning" },
  { value: "cooking-home-chef", label: "Cooking / Home Chef" },
  { value: "decking", label: "Decking" },
  { value: "draftsman", label: "Draftsman" },
  { value: "driver-chauffeur", label: "Driver / Chauffeur Services" },
  { value: "events", label: "Events & Entertainment" },
  { value: "flooring-services", label: "Flooring Services" },
  { value: "florist", label: "Florist" },
  { value: "gardening", label: "Gardening" },
  { value: "gate-installation", label: "Gate Installation" },
  { value: "handyperson", label: "Handyperson" },
  { value: "home-automation", label: "Home Automation" },
  { value: "home-theatre-services", label: "Home Theatre Services" },
  { value: "interior-architecture", label: "Interior & Architecture" },
  { value: "laundry-ironing", label: "Laundry & Ironing" },
  { value: "marketing", label: "Marketing & Design" },
  { value: "moving", label: "Moving & Delivery" },
  { value: "pet-care", label: "Pet Care" },
  { value: "photography", label: "Photography" },
  { value: "receptionist-services", label: "Receptionist Services" },
  { value: "security-services", label: "Security Services" },
  { value: "senior-care", label: "Senior Care / Elder Care" },
  { value: "sharpening-services", label: "Sharpening Services" },
  { value: "tech", label: "Tech Support" },
  { value: "tutoring", label: "Tutoring" },
  { value: "water-tanker", label: "Water & Tanker Services" },
  { value: "writing-services", label: "Writing Services" },
  { value: "other", label: "Other" },
];
