"use client";

/**
 * AadhaarUploadDialog
 *
 * Stepped dialog for admin to upload Aadhaar photos on behalf of a user.
 *
 * Step 1 → upload front side  (uses the sessionId provided by parent)
 * Step 2 → upload back side
 * After back side: backend writes to KYC vault bucket, upserts KycReview,
 *   and fires aadhaar_verification_under_review notification to the assigned
 *   operations admin via the existing cyclic round-robin assignment.
 *
 * Re-upload: parent passes a fresh nextSessionId so the new batch lands in a
 *   new prefix folder.  pickLatestVaultSideKeys on the backend sorts by
 *   lastModified and only shows the newest front+back pair in the review panel.
 */

import { useCallback, useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
  CheckCircle2,
  CloudUpload,
  FileImage,
  Loader2,
  RefreshCw,
} from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { uploadAadhaarDocument } from "@/lib/api/kyc-reviews";

type UploadStep = "front" | "back" | "done";

export interface AadhaarUploadDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  userId: string;
  userName?: string;
  /** Fresh session ID generated by the server — each batch uses a unique folder */
  sessionId: string;
  /** Whether photos were previously uploaded (changes title/description) */
  isReupload?: boolean;
}

interface FilePreview {
  file: File;
  previewUrl: string;
}

// ── Drop zone ─────────────────────────────────────────────────────────────────

function DropZone({
  label,
  preview,
  onFile,
  disabled,
}: {
  label: string;
  preview: FilePreview | null;
  onFile: (file: File) => void;
  disabled?: boolean;
}) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [dragging, setDragging] = useState(false);

  const handleFiles = useCallback(
    (files: FileList | null) => {
      if (!files || files.length === 0) return;
      const file = files[0];
      if (!file.type.startsWith("image/")) {
        toast.error("Only image files are accepted (JPEG, PNG, WEBP)");
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        toast.error("File must be under 10 MB");
        return;
      }
      onFile(file);
    },
    [onFile],
  );

  return (
    <div
      role="button"
      tabIndex={disabled ? -1 : 0}
      aria-label={`Upload ${label}`}
      className={[
        "relative flex flex-col items-center justify-center rounded-xl border-2 border-dashed transition-colors cursor-pointer select-none",
        dragging
          ? "border-amber-400 bg-amber-50"
          : "border-gray-300 hover:border-amber-400 hover:bg-amber-50/40",
        disabled ? "pointer-events-none opacity-50" : "",
        preview ? "h-64" : "h-44",
      ].join(" ")}
      onClick={() => !disabled && inputRef.current?.click()}
      onKeyDown={(e) => {
        if ((e.key === "Enter" || e.key === " ") && !disabled)
          inputRef.current?.click();
      }}
      onDragOver={(e) => {
        e.preventDefault();
        if (!disabled) setDragging(true);
      }}
      onDragLeave={() => setDragging(false)}
      onDrop={(e) => {
        e.preventDefault();
        setDragging(false);
        if (!disabled) handleFiles(e.dataTransfer.files);
      }}
    >
      <input
        ref={inputRef}
        type="file"
        accept="image/*"
        className="sr-only"
        disabled={disabled}
        onChange={(e) => handleFiles(e.target.files)}
      />

      {preview ? (
        <>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={preview.previewUrl}
            alt={label}
            className="h-full w-full rounded-xl object-contain"
          />
          <div className="absolute inset-0 flex items-end justify-center rounded-xl bg-gradient-to-t from-black/50 pb-3">
            <p className="text-xs text-white font-medium">
              {label} — click to replace
            </p>
          </div>
        </>
      ) : (
        <div className="flex flex-col items-center gap-2 px-4 text-center">
          <CloudUpload className="h-9 w-9 text-gray-400" />
          <p className="text-sm font-medium text-gray-700">{label}</p>
          <p className="text-xs text-gray-400">
            Click or drag &amp; drop · JPEG / PNG / WEBP · max 10 MB
          </p>
        </div>
      )}
    </div>
  );
}

// ── Step indicator ────────────────────────────────────────────────────────────

function StepIndicator({ step }: { step: UploadStep }) {
  const steps: { id: UploadStep; label: string }[] = [
    { id: "front", label: "Front side" },
    { id: "back", label: "Back side" },
    { id: "done", label: "Done" },
  ];
  const activeIdx = steps.findIndex((s) => s.id === step);

  return (
    <ol className="flex items-center">
      {steps.map((s, idx) => {
        const done = idx < activeIdx;
        const active = idx === activeIdx;
        return (
          <li key={s.id} className="flex items-center">
            <div className="flex flex-col items-center">
              <div
                className={[
                  "flex h-7 w-7 items-center justify-center rounded-full border-2 text-xs font-semibold transition-colors",
                  done
                    ? "border-amber-500 bg-amber-500 text-white"
                    : active
                      ? "border-amber-500 bg-white text-amber-600"
                      : "border-gray-300 bg-white text-gray-400",
                ].join(" ")}
              >
                {done ? <CheckCircle2 className="h-4 w-4" /> : idx + 1}
              </div>
              <span
                className={[
                  "mt-1 text-[10px] font-medium",
                  active
                    ? "text-amber-600"
                    : done
                      ? "text-amber-500"
                      : "text-gray-400",
                ].join(" ")}
              >
                {s.label}
              </span>
            </div>
            {idx < steps.length - 1 && (
              <div
                className={[
                  "mb-4 h-0.5 w-12 transition-colors",
                  idx < activeIdx ? "bg-amber-400" : "bg-gray-200",
                ].join(" ")}
              />
            )}
          </li>
        );
      })}
    </ol>
  );
}

// ── Main dialog ───────────────────────────────────────────────────────────────

export function AadhaarUploadDialog({
  open,
  onOpenChange,
  userId,
  userName,
  sessionId,
  isReupload = false,
}: AadhaarUploadDialogProps) {
  const queryClient = useQueryClient();
  const [step, setStep] = useState<UploadStep>("front");
  const [frontPreview, setFrontPreview] = useState<FilePreview | null>(null);
  const [backPreview, setBackPreview] = useState<FilePreview | null>(null);

  const makePreview = (file: File): FilePreview => ({
    file,
    previewUrl: URL.createObjectURL(file),
  });

  const handleFrontFile = useCallback((file: File) => {
    setFrontPreview((prev) => {
      if (prev) URL.revokeObjectURL(prev.previewUrl);
      return makePreview(file);
    });
  }, []);

  const handleBackFile = useCallback((file: File) => {
    setBackPreview((prev) => {
      if (prev) URL.revokeObjectURL(prev.previewUrl);
      return makePreview(file);
    });
  }, []);

  const reset = useCallback(() => {
    if (frontPreview) URL.revokeObjectURL(frontPreview.previewUrl);
    if (backPreview) URL.revokeObjectURL(backPreview.previewUrl);
    setFrontPreview(null);
    setBackPreview(null);
    setStep("front");
  }, [frontPreview, backPreview]);

  const handleClose = useCallback(
    (isOpen: boolean) => {
      if (!isOpen) reset();
      onOpenChange(isOpen);
    },
    [reset, onOpenChange],
  );

  // ── Front upload ────────────────────────────────────────────────────────────
  const frontMutation = useMutation({
    mutationFn: () => {
      if (!frontPreview) throw new Error("Please select the front side image");
      return uploadAadhaarDocument(userId, "front", frontPreview.file, sessionId);
    },
    onSuccess: () => {
      toast.success("Front side uploaded — now upload the back side");
      setStep("back");
    },
    onError: (err: Error) =>
      toast.error(err.message || "Failed to upload front side"),
  });

  // ── Back upload ─────────────────────────────────────────────────────────────
  const backMutation = useMutation({
    mutationFn: () => {
      if (!backPreview) throw new Error("Please select the back side image");
      return uploadAadhaarDocument(userId, "back", backPreview.file, sessionId);
    },
    onSuccess: () => {
      toast.success(
        "Both photos uploaded — operations admin notified for review",
      );
      setStep("done");
      // Refresh upload-status so button label updates in the parent
      queryClient.invalidateQueries({
        queryKey: ["aadhaar-upload-status", userId],
      });
      queryClient.invalidateQueries({ queryKey: ["kyc-reviews"] });
      queryClient.invalidateQueries({ queryKey: ["user", userId] });
    },
    onError: (err: Error) =>
      toast.error(err.message || "Failed to upload back side"),
  });

  const isUploading = frontMutation.isPending || backMutation.isPending;

  const title = isReupload ? "Re-upload Aadhaar Photos" : "Upload Aadhaar Photos";
  const description = isReupload
    ? `Uploading new photos for ${userName ?? "this user"} will replace the previous submission in the review queue. Only the latest front and back photos will be visible to the reviewer.`
    : `Upload front and back photos of ${userName ? `${userName}'s` : "the"} Aadhaar card. The operations admin will be notified once both sides are uploaded.`;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileImage className="h-5 w-5 text-amber-500" />
            {title}
          </DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>

        {/* Step indicator */}
        <div className="flex justify-center py-1">
          <StepIndicator step={step} />
        </div>

        {/* ── Step: front ────────────────────────────────────────────────────── */}
        {step === "front" && (
          <div className="space-y-4">
            <DropZone
              label="Front side of Aadhaar"
              preview={frontPreview}
              onFile={handleFrontFile}
              disabled={isUploading}
            />
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => handleClose(false)}
                disabled={isUploading}
              >
                Cancel
              </Button>
              <Button
                onClick={() => frontMutation.mutate()}
                disabled={!frontPreview || isUploading}
                className="bg-amber-500 hover:bg-amber-600 text-white"
              >
                {frontMutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Uploading…
                  </>
                ) : (
                  "Upload front side"
                )}
              </Button>
            </DialogFooter>
          </div>
        )}

        {/* ── Step: back ─────────────────────────────────────────────────────── */}
        {step === "back" && (
          <div className="space-y-4">
            {/* Confirmation chip for uploaded front */}
            {frontPreview && (
              <div className="flex items-center gap-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={frontPreview.previewUrl}
                  alt="Front"
                  className="h-10 w-14 rounded object-cover border border-amber-200"
                />
                <div>
                  <p className="text-xs font-semibold text-amber-700">
                    Front side uploaded ✓
                  </p>
                  <p className="text-xs text-amber-600">
                    Now upload the back side
                  </p>
                </div>
                <CheckCircle2 className="ml-auto h-5 w-5 text-amber-500 shrink-0" />
              </div>
            )}

            <DropZone
              label="Back side of Aadhaar"
              preview={backPreview}
              onFile={handleBackFile}
              disabled={isUploading}
            />

            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setStep("front")}
                disabled={isUploading}
              >
                ← Back
              </Button>
              <Button
                onClick={() => backMutation.mutate()}
                disabled={!backPreview || isUploading}
                className="bg-amber-500 hover:bg-amber-600 text-white"
              >
                {backMutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Uploading…
                  </>
                ) : (
                  "Upload back side & notify"
                )}
              </Button>
            </DialogFooter>
          </div>
        )}

        {/* ── Step: done ─────────────────────────────────────────────────────── */}
        {step === "done" && (
          <div className="space-y-5">
            <div className="flex flex-col items-center gap-3 py-4 text-center">
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-green-50 ring-4 ring-green-100">
                <CheckCircle2 className="h-9 w-9 text-green-500" />
              </div>
              <div>
                <p className="text-base font-semibold text-gray-900">
                  Photos submitted for review
                </p>
                <p className="mt-1 text-sm text-gray-500">
                  Both Aadhaar photos have been stored in the KYC vault. The
                  assigned operations admin has been notified and this case
                  will appear in the KYC Reviews queue with the latest images.
                </p>
              </div>
            </div>

            {/* Preview thumbnails */}
            <div className="grid grid-cols-2 gap-3">
              {frontPreview && (
                <div className="overflow-hidden rounded-lg border">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={frontPreview.previewUrl}
                    alt="Aadhaar front"
                    className="h-36 w-full object-contain bg-gray-50"
                  />
                  <p className="py-1.5 text-center text-xs font-medium text-gray-600 border-t">
                    Front side
                  </p>
                </div>
              )}
              {backPreview && (
                <div className="overflow-hidden rounded-lg border">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={backPreview.previewUrl}
                    alt="Aadhaar back"
                    className="h-36 w-full object-contain bg-gray-50"
                  />
                  <p className="py-1.5 text-center text-xs font-medium text-gray-600 border-t">
                    Back side
                  </p>
                </div>
              )}
            </div>

            <DialogFooter>
              <Button onClick={() => handleClose(false)}>Close</Button>
            </DialogFooter>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
